/**
 * Auto-generated by scripts/generate-env-config.mjs on 2025-11-13T12:35:16.127Z
 * Do NOT commit this file.
 */
window.__ENV__ = window.__ENV__ || {};
Object.assign(window.__ENV__, {
  "AZURE_CLIENT_ID": "ed17eba6-3f5d-42bf-866e-01fc039865d6",
  "AZURE_TENANT_ID": "85795021-1de9-44cf-9dd4-21c3cfce52c5",
  "AZURE_REDIRECT_URI": "https://christopheredlly.github.io/Licencas",
  "AZURE_AUTHORITY": "https://login.microsoftonline.com/85795021-1de9-44cf-9dd4-21c3cfce52c5",
  "AZURE_SCOPES": [
    "User.Read",
    "Files.Read.All"
  ]
});
