/**
 * Auto-generated by scripts/generate-env-config.mjs on 2025-11-13T13:21:29.387Z
 * Do NOT commit this file.
 */
window.__ENV__ = window.__ENV__ || {};
Object.assign(window.__ENV__, {
  "AZURE_CLIENT_ID": "ed17eba6-3f5d-42bf-866e-01fc039865d6",
  "AZURE_TENANT_ID": "85795021-1de9-44cf-9dd4-21c3cfce52c5",
  "AZURE_REDIRECT_URI": "https://christopheredlly.github.io/Licencas",
  "AZURE_AUTHORITY": "https://login.microsoftonline.com/85795021-1de9-44cf-9dd4-21c3cfce52c5",
  "AZURE_SCOPES": [
    "User.Read",
    "Files.Read"
  ]
  ,
  // Optional central configuration to allow automatic, non-public resolution of the SharePoint file
  // If these values are present, users do NOT need to paste any link in the UI.
  "AZURE_SITE_HOSTNAME": "sefazsegovbr-my.sharepoint.com", // derived from your link
  "AZURE_SITE_PATH": "personal/christopher_caldas_fazenda_se_gov_br", // derived from your link
  "AZURE_FILE_RELATIVE_PATH": "Documents/NOTIFICACAO DE LICENÇA PRÊMIO-3 VERSÃO ATUAL-3.xls", // guessed common OneDrive folder (confirm if in root or another folder)
  "AZURE_TABLE_NAME": "BD_LPREMIO" // worksheet/table name you provided (if table name differs, update this)
});